
 #eureka配置
#eureka:
 #     client:
 #       serviceUrl:
 #         defaultZone: http://localhost:8761/eureka/
server:
      port: 8087
 ##线程池配置##
threadpool:
    core:
      pool:
        size: 10
    max:
      pool:
        size: 20
    queue:
        capacity: 1000
    keep:
       alive:
         seconds: 300
   
spring:

  application:
        name: service-hi

   ##Druid##
  datasource:
      type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
      username: root
      password: 
      initialSize: 5
      minIdle: 5
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      useGlobalDataSourceStat: true
  ##视图解析器##
  mvc:
    view:
      prefix: /WEB-INF/views
      suffix: .ftl
      

  
 #redis配置
  redis:
  #  数据库索引
      database: 0
  #    服务器地址
      host: 127.0.0.1
  #    服务器连接端口
      port: 6379
  #    链接密码
      password:
  #   最大连接数（负值表示没有限制）
      max-active: 8
  #      最大阻塞等待时间（负值表示没有限制）
      max-wait:  -1
  #      最大空闲链接
      max-idle: 8
  #      最小空闲链接
      min-idle: 0
  #    链接超时时间（毫秒）
      timeout: 0
  debug: true
  
#api2doc:
   # enabled : true 
  #  title: Api2Doc示例项目——接口文档
  #  icon: https://spring.io/img/homepage/icon-spring-framework.svg

